stages:
  - test
  - deploy

test:
  stage: test
  image: jitesoft/node-base
  variables:
    NODE_ENV: development
  before_script:
    - npm install
  script:
    - npm run test

deploy:
  stage: deploy
  image: jitesoft/node-base:latest
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm whoami
    - npm install --dev
    - npm run build:prod
    - npm config set git-tag-version false
    - npm version ${CI_COMMIT_TAG}
  script:
    - npm publish --access public
  after_script:
    - rm -f ~/.npmrc
  only:
    - tags
